/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerCustomerHomeRouteImport } from './routes/customer/customerHome'
import { Route as AdminAdminProductRouteImport } from './routes/admin/adminProduct'
import { Route as AdminAdminHomeRouteImport } from './routes/admin/adminHome'
import { Route as AdminAdminCategoriesRouteImport } from './routes/admin/adminCategories'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCustomerHomeRoute = CustomerCustomerHomeRouteImport.update({
  id: '/customerHome',
  path: '/customerHome',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const AdminAdminProductRoute = AdminAdminProductRouteImport.update({
  id: '/adminProduct',
  path: '/adminProduct',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminHomeRoute = AdminAdminHomeRouteImport.update({
  id: '/adminHome',
  path: '/adminHome',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/adminCategories',
  path: '/adminCategories',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/adminCategories': typeof AdminAdminCategoriesRoute
  '/admin/adminHome': typeof AdminAdminHomeRoute
  '/admin/adminProduct': typeof AdminAdminProductRoute
  '/customer/customerHome': typeof CustomerCustomerHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/adminCategories': typeof AdminAdminCategoriesRoute
  '/admin/adminHome': typeof AdminAdminHomeRoute
  '/admin/adminProduct': typeof AdminAdminProductRoute
  '/customer/customerHome': typeof CustomerCustomerHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/adminCategories': typeof AdminAdminCategoriesRoute
  '/admin/adminHome': typeof AdminAdminHomeRoute
  '/admin/adminProduct': typeof AdminAdminProductRoute
  '/customer/customerHome': typeof CustomerCustomerHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/register'
    | '/admin/adminCategories'
    | '/admin/adminHome'
    | '/admin/adminProduct'
    | '/customer/customerHome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customer'
    | '/register'
    | '/admin/adminCategories'
    | '/admin/adminHome'
    | '/admin/adminProduct'
    | '/customer/customerHome'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/register'
    | '/admin/adminCategories'
    | '/admin/adminHome'
    | '/admin/adminProduct'
    | '/customer/customerHome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/customerHome': {
      id: '/customer/customerHome'
      path: '/customerHome'
      fullPath: '/customer/customerHome'
      preLoaderRoute: typeof CustomerCustomerHomeRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/admin/adminProduct': {
      id: '/admin/adminProduct'
      path: '/adminProduct'
      fullPath: '/admin/adminProduct'
      preLoaderRoute: typeof AdminAdminProductRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adminHome': {
      id: '/admin/adminHome'
      path: '/adminHome'
      fullPath: '/admin/adminHome'
      preLoaderRoute: typeof AdminAdminHomeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/adminCategories': {
      id: '/admin/adminCategories'
      path: '/adminCategories'
      fullPath: '/admin/adminCategories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminHomeRoute: typeof AdminAdminHomeRoute
  AdminAdminProductRoute: typeof AdminAdminProductRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminHomeRoute: AdminAdminHomeRoute,
  AdminAdminProductRoute: AdminAdminProductRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CustomerRouteRouteChildren {
  CustomerCustomerHomeRoute: typeof CustomerCustomerHomeRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerCustomerHomeRoute: CustomerCustomerHomeRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
